README: add generic maintenance section copied from meta-agl-core
Yocto Project compatibility requires README to specify who is the layer
maintainer and how to contribute to the layer. Otherwise yocto-check-layer
fails:

INFO: test_readme (common.CommonCheckLayer)
INFO:  ... FAIL
AssertionError: 'maintainer' not found in 'README'
AssertionError: 'patch' not found in 'README'

Bug-AGL: SPEC-4685
Change-Id: I0ca1feba1b2d56e1780c6e05c92a2b27792f6cb0
Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>