kuksa-client: fix rpm transaction conflict on python site test directory
This fixes:
Running transaction test
Error: Transaction test error:
  file /usr/lib/python3.14/site-packages/tests/__init__.py conflicts between attempted installs of kuksa-client-0.6.0-r0.corei7_64 and python3-cryptography-46.0.5-r0.corei7_64
  file /usr/lib/python3.14/site-packages/tests/__pycache__/__init__.cpython-314.pyc conflicts between attempted installs of kuksa-client-0.6.0-r0.corei7_64 and python3-cryptography-46.0.5-r0.corei7_64
  file /usr/lib/python3.14/site-packages/tests/__pycache__/conftest.cpython-314.pyc conflicts between attempted installs of kuksa-client-0.6.0-r0.corei7_64 and python3-cryptography-46.0.5-r0.corei7_64
  file /usr/lib/python3.14/site-packages/tests/conftest.py conflicts between attempted installs of kuksa-client-0.6.0-r0.corei7_64 and python3-cryptography-46.0.5-r0.corei7_64

Also remove accidentially added .new recipes and folder .

Bug-AGL: SPEC-5713
Change-Id: I285feb3ebb139e0d07baa9049770504ffe856fa3
Signed-off-by: Jan-Simon Moeller <jsmoeller@linuxfoundation.org>
Reviewed-on: https://gerrit.automotivelinux.org/gerrit/c/AGL/meta-agl/+/32058
ci-image-boot-test: Jenkins Job builder account
ci-image-build: Jenkins Job builder account
Tested-by: Jenkins Job builder account