qtwayland: disable local patch that breaks version 5.15.7
Latest meta-qt5 brings qtwayland version 5.15.7 and this causes our local
patch for client/qwaylandintegration to break the build, as the method it
uses no longer exists, it appears:

| .../tmp/work/aarch64-agl-linux/qtwayland/5.15.7+gitAUTOINC+533fff12f7-r0/git/src/client/qwaylandintegration.cpp: In member function 'void QtWaylandClient::QWaylandIntegration::reconfigureInputContext()':
| .../tmp/work/aarch64-agl-linux/qtwayland/5.15.7+gitAUTOINC+533fff12f7-r0/git/src/client/qwaylandintegration.cpp:482:19: error: 'class QtWaylandClient::QWaylandDisplay' has no member named 'mUsingInputContextFromCompositor'
|   482 |     if (mDisplay->mUsingInputContextFromCompositor)
|       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Disable local patch for now with the plan to re-evaluate it per SPEC-4770

Bug-AGL: SPEC-4768

Change-Id: I27894536d49392589c58a3c46e4b1e015c7324fb
Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>